services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Super@Password123!
    ports:
      - "1434:1433"
    volumes:
      - mssql-data:/var/opt/mssql
      
  api:
    container_name: offer-management-api
    build:
      context: ./backend 
      dockerfile: OfferManagement.Api/Dockerfile
    ports:
      - "8080:8080" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=db;Database=OfferManagementDb;User Id=sa;Password=Super@Password123!;Trusted_Connection=False;Encrypt=False;TrustServerCertificate=True;
    depends_on:
      - db 
      
volumes:
  mssql-data: